-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 22:14:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_codigo_g19
-- -----------------------------------------------------
-- Base de datos para los bootcamps de codigo

-- -----------------------------------------------------
-- Schema db_codigo_g19
--
-- Base de datos para los bootcamps de codigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_codigo_g19` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_codigo_g19` ;

-- -----------------------------------------------------
-- Table `db_codigo_g19`.`tbl_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo_g19`.`tbl_curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT,
  `curso_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`curso_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo_g19`.`tbl_bootcamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo_g19`.`tbl_bootcamp` (
  `bootcamp_id` INT NOT NULL AUTO_INCREMENT,
  `bootcamp_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`bootcamp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo_g19`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo_g19`.`tbl_alumno` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_nombre` VARCHAR(255) NOT NULL,
  `alumno_email` VARCHAR(255) NOT NULL,
  `alumno_celular` VARCHAR(100) NULL,
  PRIMARY KEY (`alumno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo_g19`.`tbl_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo_g19`.`tbl_matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `matricula_grupo` VARCHAR(20) NULL,
  `alumno_id` INT NOT NULL,
  `bootcamp_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  CONSTRAINT `fk_tbl_matricula_tbl_alumno`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_codigo_g19`.`tbl_alumno` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_tbl_bootcamp1`
    FOREIGN KEY (`bootcamp_id`)
    REFERENCES `db_codigo_g19`.`tbl_bootcamp` (`bootcamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo_g19`.`tbl_matricula_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo_g19`.`tbl_matricula_curso` (
  `matricula_curso_id` INT NOT NULL AUTO_INCREMENT,
  `matricula_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`matricula_curso_id`),
  CONSTRAINT `fk_tbl_matricula_curso_tbl_matricula1`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `db_codigo_g19`.`tbl_matricula` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_curso_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_codigo_g19`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
