# Generated by Django 4.1.7 on 2023-03-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='pendiente', max_length=100)),
            ],
        ),
    ]
