-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 20:05:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_factura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_factura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_factura` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_factura` ;

-- -----------------------------------------------------
-- Table `db_factura`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_rsocial` VARCHAR(255) NOT NULL,
  `cliente_ruc` VARCHAR(20) NOT NULL,
  `cliente_direccion` LONGTEXT NOT NULL,
  `cliente_estado` CHAR(1) NOT NULL DEFAULT '1',
  `cliente_fecha_log` TIMESTAMP NOT NULL DEFAULT NOW(),
  `cliente_usuario_log` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `producto_codigo` VARCHAR(255) NOT NULL,
  `producto_precio` DOUBLE NOT NULL,
  `producto_estado` CHAR(1) NOT NULL DEFAULT '1',
  `producto_fecha_log` TIMESTAMP NOT NULL DEFAULT NOW(),
  `producto_usuario_log` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_factura_cab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_factura_cab` (
  `factura_cab_id` INT NOT NULL AUTO_INCREMENT,
  `factura_cab_serie` VARCHAR(20) NOT NULL,
  `factura_cab_nro` VARCHAR(255) NOT NULL,
  `factura_cab_fvencimiento` DATE NOT NULL,
  `factura_cab_femision` DATE NOT NULL,
  `factura_cab_tipo_moneda` VARCHAR(45) NOT NULL DEFAULT 'SOLES',
  `factura_cab_observacion` LONGTEXT NULL,
  `factura_cab_valorventa` DOUBLE NOT NULL,
  `factura_cab_valorigv` DOUBLE NOT NULL,
  `factura_cab_valortotal` DOUBLE NOT NULL,
  `factura_cab_estado` CHAR(1) NOT NULL DEFAULT '1',
  `factura_cab_fecha_log` TIMESTAMP NOT NULL,
  `factura_cab_usuario_log` VARCHAR(255) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`factura_cab_id`),
  CONSTRAINT `fk_tbl_factura_cab_tbl_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_factura`.`tbl_cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_factura_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_factura_det` (
  `factura_det_id` INT NOT NULL AUTO_INCREMENT,
  `factura_det_precio` DOUBLE NOT NULL,
  `factura_det_cantidad` DOUBLE NOT NULL,
  `factura_det_subtotal` DOUBLE NOT NULL,
  `factura_det_fecha_log` TIMESTAMP NOT NULL DEFAULT NOW(),
  `factura_det_usuario_log` VARCHAR(255) NOT NULL,
  `producto_id` INT NOT NULL,
  `factura_cab_id` INT NOT NULL,
  PRIMARY KEY (`factura_det_id`),
  CONSTRAINT `fk_tbl_factura_det_tbl_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `db_factura`.`tbl_producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_det_tbl_factura_cab1`
    FOREIGN KEY (`factura_cab_id`)
    REFERENCES `db_factura`.`tbl_factura_cab` (`factura_cab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
