# Generated by Django 3.2 on 2023-04-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_rsocial', models.CharField(max_length=255)),
                ('cliente_ruc', models.CharField(max_length=20)),
                ('cliente_direccion', models.TextField()),
                ('cliente_estado', models.CharField(max_length=1)),
                ('cliente_fecha_log', models.DateTimeField()),
                ('cliente_usuario_log', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaCab',
            fields=[
                ('factura_cab_id', models.AutoField(primary_key=True, serialize=False)),
                ('factura_cab_serie', models.CharField(max_length=20)),
                ('factura_cab_nro', models.CharField(max_length=255)),
                ('factura_cab_fvencimiento', models.DateField()),
                ('factura_cab_femision', models.DateField()),
                ('factura_cab_tipo_moneda', models.CharField(max_length=45)),
                ('factura_cab_observacion', models.TextField(blank=True, null=True)),
                ('factura_cab_valorventa', models.FloatField()),
                ('factura_cab_valorigv', models.FloatField()),
                ('factura_cab_valortotal', models.FloatField()),
                ('factura_cab_estado', models.CharField(max_length=1)),
                ('factura_cab_fecha_log', models.DateTimeField()),
                ('factura_cab_usuario_log', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_factura_cab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaDet',
            fields=[
                ('factura_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('factura_det_precio', models.FloatField()),
                ('factura_det_cantidad', models.FloatField()),
                ('factura_det_subtotal', models.FloatField()),
                ('factura_det_fecha_log', models.DateTimeField()),
                ('factura_det_usuario_log', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_factura_det',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_codigo', models.CharField(max_length=255)),
                ('producto_precio', models.FloatField()),
                ('producto_estado', models.CharField(default='1', max_length=1)),
                ('producto_fecha_log', models.DateTimeField(auto_now_add=True)),
                ('producto_usuario_log', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_producto',
                'managed': False,
            },
        ),
    ]
