# Generated by Django 4.1.7 on 2023-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('Terminado', 'Terminado')], max_length=20)),
            ],
        ),
    ]
