"""tabla nivel

Revision ID: ead06c1c6c07
Revises: 0be6a1f45028
Create Date: 2023-03-13 22:45:35.639669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead06c1c6c07'
down_revision = '0be6a1f45028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_nivel',
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('nivel_descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nivel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_nivel')
    # ### end Alembic commands ###
