"""curso

Revision ID: f3d39d8437ea
Revises: ead06c1c6c07
Create Date: 2023-03-13 22:59:00.277645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d39d8437ea'
down_revision = 'ead06c1c6c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_autor',
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('autor_nombre', sa.String(length=200), nullable=False),
    sa.Column('autor_foto', sa.String(length=200), nullable=True),
    sa.Column('autor_descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('autor_id')
    )
    op.create_table('tbl_curso',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('curso_titulo', sa.String(length=200), nullable=False),
    sa.Column('curso_descripcion', sa.Text(), nullable=True),
    sa.Column('curso_fecharegistro', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nivel_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['tbl_autor.autor_id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['tbl_categoria.categoria_id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['tbl_nivel.nivel_id'], ),
    sa.PrimaryKeyConstraint('curso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_curso')
    op.drop_table('tbl_autor')
    # ### end Alembic commands ###
