# Generated by Django 4.1.7 on 2023-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
            ],
        ),
    ]
